// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Room.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetMessage.Room {

  /// <summary>Holder for reflection information generated from Room.proto</summary>
  public static partial class RoomReflection {

    #region Descriptor
    /// <summary>File descriptor for Room.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RoomReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpSb29tLnByb3RvEgRUZXN0GgpFbnVtLnByb3RvGhBQbGF5ZXJJbmZvLnBy",
            "b3RvIrABCghSb29tUGFjaxIOCgZyb29tSWQYASABKAkSIAoIRnVuY0NvZGUY",
            "AiABKA4yDi5UZXN0LkZ1bmNDb2RlEiQKCnJldHVybkNvZGUYAyABKA4yEC5U",
            "ZXN0LlJldHVybkNvZGUSKAoMUm9vbVNldHRpbmdzGAQgASgLMhIuVGVzdC5S",
            "b29tU2V0dGluZ3MSIgoJUm9vbUV2ZW50GAUgASgLMg8uVGVzdC5Sb29tRXZl",
            "bnQitwEKCVJvb21FdmVudBITCgtzcmNQbGF5ZXJJcBgBIAEoCRIiCglldmVu",
            "dENvZGUYAiABKA4yDy5UZXN0LkV2ZW50Q29kZRIkCgpwbGF5ZXJJbmZvGAMg",
            "ASgLMhAuVGVzdC5QbGF5ZXJJbmZvEigKDFJvb21TZXR0aW5ncxgEIAEoCzIS",
            "LlRlc3QuUm9vbVNldHRpbmdzEiEKB3BsYXllcnMYBSADKAsyEC5UZXN0LlBs",
            "YXllckluZm8iHQoMUm9vbVNldHRpbmdzEg0KBW1hcElkGAEgASgFKlgKCUV2",
            "ZW50Q29kZRINCglFdmVudE5vbmUQABITCg9QbGF5ZXJFbnRlclJvb20QARIS",
            "Cg5QbGF5ZXJFeGl0Um9vbRACEhMKD1BsYXllclN0YXJ0R2FtZRADKjUKCEZ1",
            "bmNDb2RlEgwKCEZ1bmNOb25lEAASDAoIRXhpdFJvb20QARINCglTdGFydEdh",
            "bWUQAkISqgIPTmV0TWVzc2FnZS5Sb29tYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NetMessage.Enum.EnumReflection.Descriptor, global::NetMessage.PlayerInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetMessage.Room.EventCode), typeof(global::NetMessage.Room.FuncCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMessage.Room.RoomPack), global::NetMessage.Room.RoomPack.Parser, new[]{ "RoomId", "FuncCode", "ReturnCode", "RoomSettings", "RoomEvent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMessage.Room.RoomEvent), global::NetMessage.Room.RoomEvent.Parser, new[]{ "SrcPlayerIp", "EventCode", "PlayerInfo", "RoomSettings", "Players" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMessage.Room.RoomSettings), global::NetMessage.Room.RoomSettings.Parser, new[]{ "MapId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EventCode {
    [pbr::OriginalName("EventNone")] EventNone = 0,
    [pbr::OriginalName("PlayerEnterRoom")] PlayerEnterRoom = 1,
    [pbr::OriginalName("PlayerExitRoom")] PlayerExitRoom = 2,
    [pbr::OriginalName("PlayerStartGame")] PlayerStartGame = 3,
  }

  public enum FuncCode {
    [pbr::OriginalName("FuncNone")] FuncNone = 0,
    [pbr::OriginalName("ExitRoom")] ExitRoom = 1,
    [pbr::OriginalName("StartGame")] StartGame = 2,
  }

  #endregion

  #region Messages
  public sealed partial class RoomPack : pb::IMessage<RoomPack>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomPack> _parser = new pb::MessageParser<RoomPack>(() => new RoomPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMessage.Room.RoomReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomPack(RoomPack other) : this() {
      roomId_ = other.roomId_;
      funcCode_ = other.funcCode_;
      returnCode_ = other.returnCode_;
      roomSettings_ = other.roomSettings_ != null ? other.roomSettings_.Clone() : null;
      roomEvent_ = other.roomEvent_ != null ? other.roomEvent_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomPack Clone() {
      return new RoomPack(this);
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private string roomId_ = "";
    /// <summary>
    ///发生事件的房间号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomId {
      get { return roomId_; }
      set {
        roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FuncCode" field.</summary>
    public const int FuncCodeFieldNumber = 2;
    private global::NetMessage.Room.FuncCode funcCode_ = global::NetMessage.Room.FuncCode.FuncNone;
    /// <summary>
    ///单客户端与服务端的通信
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Room.FuncCode FuncCode {
      get { return funcCode_; }
      set {
        funcCode_ = value;
      }
    }

    /// <summary>Field number for the "returnCode" field.</summary>
    public const int ReturnCodeFieldNumber = 3;
    private global::NetMessage.Enum.ReturnCode returnCode_ = global::NetMessage.Enum.ReturnCode.ReturnNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Enum.ReturnCode ReturnCode {
      get { return returnCode_; }
      set {
        returnCode_ = value;
      }
    }

    /// <summary>Field number for the "RoomSettings" field.</summary>
    public const int RoomSettingsFieldNumber = 4;
    private global::NetMessage.Room.RoomSettings roomSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Room.RoomSettings RoomSettings {
      get { return roomSettings_; }
      set {
        roomSettings_ = value;
      }
    }

    /// <summary>Field number for the "RoomEvent" field.</summary>
    public const int RoomEventFieldNumber = 5;
    private global::NetMessage.Room.RoomEvent roomEvent_;
    /// <summary>
    ///用于服务器广播给其他玩家
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Room.RoomEvent RoomEvent {
      get { return roomEvent_; }
      set {
        roomEvent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (FuncCode != other.FuncCode) return false;
      if (ReturnCode != other.ReturnCode) return false;
      if (!object.Equals(RoomSettings, other.RoomSettings)) return false;
      if (!object.Equals(RoomEvent, other.RoomEvent)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
      if (FuncCode != global::NetMessage.Room.FuncCode.FuncNone) hash ^= FuncCode.GetHashCode();
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) hash ^= ReturnCode.GetHashCode();
      if (roomSettings_ != null) hash ^= RoomSettings.GetHashCode();
      if (roomEvent_ != null) hash ^= RoomEvent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomId);
      }
      if (FuncCode != global::NetMessage.Room.FuncCode.FuncNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) FuncCode);
      }
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ReturnCode);
      }
      if (roomSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomSettings);
      }
      if (roomEvent_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RoomEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomId);
      }
      if (FuncCode != global::NetMessage.Room.FuncCode.FuncNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) FuncCode);
      }
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ReturnCode);
      }
      if (roomSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomSettings);
      }
      if (roomEvent_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RoomEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
      }
      if (FuncCode != global::NetMessage.Room.FuncCode.FuncNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FuncCode);
      }
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReturnCode);
      }
      if (roomSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomSettings);
      }
      if (roomEvent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomPack other) {
      if (other == null) {
        return;
      }
      if (other.RoomId.Length != 0) {
        RoomId = other.RoomId;
      }
      if (other.FuncCode != global::NetMessage.Room.FuncCode.FuncNone) {
        FuncCode = other.FuncCode;
      }
      if (other.ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        ReturnCode = other.ReturnCode;
      }
      if (other.roomSettings_ != null) {
        if (roomSettings_ == null) {
          RoomSettings = new global::NetMessage.Room.RoomSettings();
        }
        RoomSettings.MergeFrom(other.RoomSettings);
      }
      if (other.roomEvent_ != null) {
        if (roomEvent_ == null) {
          RoomEvent = new global::NetMessage.Room.RoomEvent();
        }
        RoomEvent.MergeFrom(other.RoomEvent);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RoomId = input.ReadString();
            break;
          }
          case 16: {
            FuncCode = (global::NetMessage.Room.FuncCode) input.ReadEnum();
            break;
          }
          case 24: {
            ReturnCode = (global::NetMessage.Enum.ReturnCode) input.ReadEnum();
            break;
          }
          case 34: {
            if (roomSettings_ == null) {
              RoomSettings = new global::NetMessage.Room.RoomSettings();
            }
            input.ReadMessage(RoomSettings);
            break;
          }
          case 42: {
            if (roomEvent_ == null) {
              RoomEvent = new global::NetMessage.Room.RoomEvent();
            }
            input.ReadMessage(RoomEvent);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RoomId = input.ReadString();
            break;
          }
          case 16: {
            FuncCode = (global::NetMessage.Room.FuncCode) input.ReadEnum();
            break;
          }
          case 24: {
            ReturnCode = (global::NetMessage.Enum.ReturnCode) input.ReadEnum();
            break;
          }
          case 34: {
            if (roomSettings_ == null) {
              RoomSettings = new global::NetMessage.Room.RoomSettings();
            }
            input.ReadMessage(RoomSettings);
            break;
          }
          case 42: {
            if (roomEvent_ == null) {
              RoomEvent = new global::NetMessage.Room.RoomEvent();
            }
            input.ReadMessage(RoomEvent);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RoomEvent : pb::IMessage<RoomEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomEvent> _parser = new pb::MessageParser<RoomEvent>(() => new RoomEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMessage.Room.RoomReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomEvent(RoomEvent other) : this() {
      srcPlayerIp_ = other.srcPlayerIp_;
      eventCode_ = other.eventCode_;
      playerInfo_ = other.playerInfo_ != null ? other.playerInfo_.Clone() : null;
      roomSettings_ = other.roomSettings_ != null ? other.roomSettings_.Clone() : null;
      players_ = other.players_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomEvent Clone() {
      return new RoomEvent(this);
    }

    /// <summary>Field number for the "srcPlayerIp" field.</summary>
    public const int SrcPlayerIpFieldNumber = 1;
    private string srcPlayerIp_ = "";
    /// <summary>
    ///发出事件的源玩家,由服务端接收消息后填充
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcPlayerIp {
      get { return srcPlayerIp_; }
      set {
        srcPlayerIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "eventCode" field.</summary>
    public const int EventCodeFieldNumber = 2;
    private global::NetMessage.Room.EventCode eventCode_ = global::NetMessage.Room.EventCode.EventNone;
    /// <summary>
    ///发生了什么事
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Room.EventCode EventCode {
      get { return eventCode_; }
      set {
        eventCode_ = value;
      }
    }

    /// <summary>Field number for the "playerInfo" field.</summary>
    public const int PlayerInfoFieldNumber = 3;
    private global::NetMessage.PlayerInfo playerInfo_;
    /// <summary>
    ///通知其他新玩家进入，新玩家的信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.PlayerInfo PlayerInfo {
      get { return playerInfo_; }
      set {
        playerInfo_ = value;
      }
    }

    /// <summary>Field number for the "RoomSettings" field.</summary>
    public const int RoomSettingsFieldNumber = 4;
    private global::NetMessage.Room.RoomSettings roomSettings_;
    /// <summary>
    ///用于开始游戏
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Room.RoomSettings RoomSettings {
      get { return roomSettings_; }
      set {
        roomSettings_ = value;
      }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 5;
    private static readonly pb::FieldCodec<global::NetMessage.PlayerInfo> _repeated_players_codec
        = pb::FieldCodec.ForMessage(42, global::NetMessage.PlayerInfo.Parser);
    private readonly pbc::RepeatedField<global::NetMessage.PlayerInfo> players_ = new pbc::RepeatedField<global::NetMessage.PlayerInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::NetMessage.PlayerInfo> Players {
      get { return players_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcPlayerIp != other.SrcPlayerIp) return false;
      if (EventCode != other.EventCode) return false;
      if (!object.Equals(PlayerInfo, other.PlayerInfo)) return false;
      if (!object.Equals(RoomSettings, other.RoomSettings)) return false;
      if(!players_.Equals(other.players_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcPlayerIp.Length != 0) hash ^= SrcPlayerIp.GetHashCode();
      if (EventCode != global::NetMessage.Room.EventCode.EventNone) hash ^= EventCode.GetHashCode();
      if (playerInfo_ != null) hash ^= PlayerInfo.GetHashCode();
      if (roomSettings_ != null) hash ^= RoomSettings.GetHashCode();
      hash ^= players_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcPlayerIp.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcPlayerIp);
      }
      if (EventCode != global::NetMessage.Room.EventCode.EventNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EventCode);
      }
      if (playerInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayerInfo);
      }
      if (roomSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomSettings);
      }
      players_.WriteTo(output, _repeated_players_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcPlayerIp.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcPlayerIp);
      }
      if (EventCode != global::NetMessage.Room.EventCode.EventNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EventCode);
      }
      if (playerInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayerInfo);
      }
      if (roomSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomSettings);
      }
      players_.WriteTo(ref output, _repeated_players_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcPlayerIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcPlayerIp);
      }
      if (EventCode != global::NetMessage.Room.EventCode.EventNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventCode);
      }
      if (playerInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerInfo);
      }
      if (roomSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomSettings);
      }
      size += players_.CalculateSize(_repeated_players_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomEvent other) {
      if (other == null) {
        return;
      }
      if (other.SrcPlayerIp.Length != 0) {
        SrcPlayerIp = other.SrcPlayerIp;
      }
      if (other.EventCode != global::NetMessage.Room.EventCode.EventNone) {
        EventCode = other.EventCode;
      }
      if (other.playerInfo_ != null) {
        if (playerInfo_ == null) {
          PlayerInfo = new global::NetMessage.PlayerInfo();
        }
        PlayerInfo.MergeFrom(other.PlayerInfo);
      }
      if (other.roomSettings_ != null) {
        if (roomSettings_ == null) {
          RoomSettings = new global::NetMessage.Room.RoomSettings();
        }
        RoomSettings.MergeFrom(other.RoomSettings);
      }
      players_.Add(other.players_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcPlayerIp = input.ReadString();
            break;
          }
          case 16: {
            EventCode = (global::NetMessage.Room.EventCode) input.ReadEnum();
            break;
          }
          case 26: {
            if (playerInfo_ == null) {
              PlayerInfo = new global::NetMessage.PlayerInfo();
            }
            input.ReadMessage(PlayerInfo);
            break;
          }
          case 34: {
            if (roomSettings_ == null) {
              RoomSettings = new global::NetMessage.Room.RoomSettings();
            }
            input.ReadMessage(RoomSettings);
            break;
          }
          case 42: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcPlayerIp = input.ReadString();
            break;
          }
          case 16: {
            EventCode = (global::NetMessage.Room.EventCode) input.ReadEnum();
            break;
          }
          case 26: {
            if (playerInfo_ == null) {
              PlayerInfo = new global::NetMessage.PlayerInfo();
            }
            input.ReadMessage(PlayerInfo);
            break;
          }
          case 34: {
            if (roomSettings_ == null) {
              RoomSettings = new global::NetMessage.Room.RoomSettings();
            }
            input.ReadMessage(RoomSettings);
            break;
          }
          case 42: {
            players_.AddEntriesFrom(ref input, _repeated_players_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RoomSettings : pb::IMessage<RoomSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomSettings> _parser = new pb::MessageParser<RoomSettings>(() => new RoomSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMessage.Room.RoomReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomSettings(RoomSettings other) : this() {
      mapId_ = other.mapId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomSettings Clone() {
      return new RoomSettings(this);
    }

    /// <summary>Field number for the "mapId" field.</summary>
    public const int MapIdFieldNumber = 1;
    private int mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapId != other.MapId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MapId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MapId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomSettings other) {
      if (other == null) {
        return;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MapId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MapId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
