// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Lobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetMessage.Lobby {

  /// <summary>Holder for reflection information generated from Lobby.proto</summary>
  public static partial class LobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for Lobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtMb2JieS5wcm90bxIEVGVzdBoKRW51bS5wcm90bxoQUGxheWVySW5mby5w",
            "cm90byKDAgoJTG9iYnlQYWNrEiAKCGZ1bmNDb2RlGAEgASgOMg4uVGVzdC5G",
            "dW5jQ29kZRIkCgpyZXR1cm5Db2RlGAIgASgOMhAuVGVzdC5SZXR1cm5Db2Rl",
            "EiIKCWVycm9yQ29kZRgDIAEoDjIPLlRlc3QuRXJyb3JDb2RlEhEKCWMyc1Jv",
            "b21JZBgEIAEoCRImCgtjMnNSb29tSW5mbxgFIAEoCzIRLlRlc3QuQzJTUm9v",
            "bUluZm8SJgoLczJjUm9vbUluZm8YBiADKAsyES5UZXN0LlMyQ1Jvb21JbmZv",
            "EicKDXMyY1BsYXllckluZm8YByADKAsyEC5UZXN0LlBsYXllckluZm8iagoL",
            "UzJDUm9vbUluZm8SDgoGUm9vbUlkGAEgASgJEhAKCFJvb21OYW1lGAIgASgJ",
            "EhAKCEhvc3ROYW1lGAMgASgJEhEKCVBsYXllck51bRgEIAEoBRIUCgxNYXhQ",
            "bGF5ZXJOdW0YBSABKAUiRwoLQzJTUm9vbUluZm8SEAoIUm9vbU5hbWUYASAB",
            "KAkSEAoISG9zdE5hbWUYAiABKAkSFAoMTWF4UGxheWVyTnVtGAMgASgFKkgK",
            "CEZ1bmNDb2RlEgwKCEZ1bmNOb25lEAASDQoJRW50ZXJSb29tEAESDgoKQ3Jl",
            "YXRlUm9vbRACEg8KC1JlZnJlc2hSb29tEAMqWQoJRXJyb3JDb2RlEg0KCUVy",
            "cm9yTm9uZRAAEhAKDE5vdEV4aXN0Um9vbRABEgoKBk1heE51bRACEg8KC0dh",
            "bWVTdGFydGVkEAMSDgoKQ3JlYXRlRmFpbBAFQhOqAhBOZXRNZXNzYWdlLkxv",
            "YmJ5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NetMessage.Enum.EnumReflection.Descriptor, global::NetMessage.PlayerInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetMessage.Lobby.FuncCode), typeof(global::NetMessage.Lobby.ErrorCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMessage.Lobby.LobbyPack), global::NetMessage.Lobby.LobbyPack.Parser, new[]{ "FuncCode", "ReturnCode", "ErrorCode", "C2SRoomId", "C2SRoomInfo", "S2CRoomInfo", "S2CPlayerInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMessage.Lobby.S2CRoomInfo), global::NetMessage.Lobby.S2CRoomInfo.Parser, new[]{ "RoomId", "RoomName", "HostName", "PlayerNum", "MaxPlayerNum" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMessage.Lobby.C2SRoomInfo), global::NetMessage.Lobby.C2SRoomInfo.Parser, new[]{ "RoomName", "HostName", "MaxPlayerNum" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FuncCode {
    [pbr::OriginalName("FuncNone")] FuncNone = 0,
    [pbr::OriginalName("EnterRoom")] EnterRoom = 1,
    [pbr::OriginalName("CreateRoom")] CreateRoom = 2,
    [pbr::OriginalName("RefreshRoom")] RefreshRoom = 3,
  }

  public enum ErrorCode {
    [pbr::OriginalName("ErrorNone")] ErrorNone = 0,
    /// <summary>
    ///FindRoom/JoinRoom
    /// </summary>
    [pbr::OriginalName("NotExistRoom")] NotExistRoom = 1,
    [pbr::OriginalName("MaxNum")] MaxNum = 2,
    [pbr::OriginalName("GameStarted")] GameStarted = 3,
    /// <summary>
    ///CreateRoom
    /// </summary>
    [pbr::OriginalName("CreateFail")] CreateFail = 5,
  }

  #endregion

  #region Messages
  public sealed partial class LobbyPack : pb::IMessage<LobbyPack>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LobbyPack> _parser = new pb::MessageParser<LobbyPack>(() => new LobbyPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LobbyPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMessage.Lobby.LobbyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LobbyPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LobbyPack(LobbyPack other) : this() {
      funcCode_ = other.funcCode_;
      returnCode_ = other.returnCode_;
      errorCode_ = other.errorCode_;
      c2SRoomId_ = other.c2SRoomId_;
      c2SRoomInfo_ = other.c2SRoomInfo_ != null ? other.c2SRoomInfo_.Clone() : null;
      s2CRoomInfo_ = other.s2CRoomInfo_.Clone();
      s2CPlayerInfo_ = other.s2CPlayerInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LobbyPack Clone() {
      return new LobbyPack(this);
    }

    /// <summary>Field number for the "funcCode" field.</summary>
    public const int FuncCodeFieldNumber = 1;
    private global::NetMessage.Lobby.FuncCode funcCode_ = global::NetMessage.Lobby.FuncCode.FuncNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Lobby.FuncCode FuncCode {
      get { return funcCode_; }
      set {
        funcCode_ = value;
      }
    }

    /// <summary>Field number for the "returnCode" field.</summary>
    public const int ReturnCodeFieldNumber = 2;
    private global::NetMessage.Enum.ReturnCode returnCode_ = global::NetMessage.Enum.ReturnCode.ReturnNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Enum.ReturnCode ReturnCode {
      get { return returnCode_; }
      set {
        returnCode_ = value;
      }
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 3;
    private global::NetMessage.Lobby.ErrorCode errorCode_ = global::NetMessage.Lobby.ErrorCode.ErrorNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Lobby.ErrorCode ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "c2sRoomId" field.</summary>
    public const int C2SRoomIdFieldNumber = 4;
    private string c2SRoomId_ = "";
    /// <summary>
    ///c2s JoinRoom
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string C2SRoomId {
      get { return c2SRoomId_; }
      set {
        c2SRoomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "c2sRoomInfo" field.</summary>
    public const int C2SRoomInfoFieldNumber = 5;
    private global::NetMessage.Lobby.C2SRoomInfo c2SRoomInfo_;
    /// <summary>
    ///c2s CreateRoom
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMessage.Lobby.C2SRoomInfo C2SRoomInfo {
      get { return c2SRoomInfo_; }
      set {
        c2SRoomInfo_ = value;
      }
    }

    /// <summary>Field number for the "s2cRoomInfo" field.</summary>
    public const int S2CRoomInfoFieldNumber = 6;
    private static readonly pb::FieldCodec<global::NetMessage.Lobby.S2CRoomInfo> _repeated_s2CRoomInfo_codec
        = pb::FieldCodec.ForMessage(50, global::NetMessage.Lobby.S2CRoomInfo.Parser);
    private readonly pbc::RepeatedField<global::NetMessage.Lobby.S2CRoomInfo> s2CRoomInfo_ = new pbc::RepeatedField<global::NetMessage.Lobby.S2CRoomInfo>();
    /// <summary>
    ///s2c RefreshRoom/s2c CreateRoom
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::NetMessage.Lobby.S2CRoomInfo> S2CRoomInfo {
      get { return s2CRoomInfo_; }
    }

    /// <summary>Field number for the "s2cPlayerInfo" field.</summary>
    public const int S2CPlayerInfoFieldNumber = 7;
    private static readonly pb::FieldCodec<global::NetMessage.PlayerInfo> _repeated_s2CPlayerInfo_codec
        = pb::FieldCodec.ForMessage(58, global::NetMessage.PlayerInfo.Parser);
    private readonly pbc::RepeatedField<global::NetMessage.PlayerInfo> s2CPlayerInfo_ = new pbc::RepeatedField<global::NetMessage.PlayerInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::NetMessage.PlayerInfo> S2CPlayerInfo {
      get { return s2CPlayerInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LobbyPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LobbyPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FuncCode != other.FuncCode) return false;
      if (ReturnCode != other.ReturnCode) return false;
      if (ErrorCode != other.ErrorCode) return false;
      if (C2SRoomId != other.C2SRoomId) return false;
      if (!object.Equals(C2SRoomInfo, other.C2SRoomInfo)) return false;
      if(!s2CRoomInfo_.Equals(other.s2CRoomInfo_)) return false;
      if(!s2CPlayerInfo_.Equals(other.s2CPlayerInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FuncCode != global::NetMessage.Lobby.FuncCode.FuncNone) hash ^= FuncCode.GetHashCode();
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) hash ^= ReturnCode.GetHashCode();
      if (ErrorCode != global::NetMessage.Lobby.ErrorCode.ErrorNone) hash ^= ErrorCode.GetHashCode();
      if (C2SRoomId.Length != 0) hash ^= C2SRoomId.GetHashCode();
      if (c2SRoomInfo_ != null) hash ^= C2SRoomInfo.GetHashCode();
      hash ^= s2CRoomInfo_.GetHashCode();
      hash ^= s2CPlayerInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FuncCode != global::NetMessage.Lobby.FuncCode.FuncNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FuncCode);
      }
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ReturnCode);
      }
      if (ErrorCode != global::NetMessage.Lobby.ErrorCode.ErrorNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrorCode);
      }
      if (C2SRoomId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(C2SRoomId);
      }
      if (c2SRoomInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(C2SRoomInfo);
      }
      s2CRoomInfo_.WriteTo(output, _repeated_s2CRoomInfo_codec);
      s2CPlayerInfo_.WriteTo(output, _repeated_s2CPlayerInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FuncCode != global::NetMessage.Lobby.FuncCode.FuncNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FuncCode);
      }
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ReturnCode);
      }
      if (ErrorCode != global::NetMessage.Lobby.ErrorCode.ErrorNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrorCode);
      }
      if (C2SRoomId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(C2SRoomId);
      }
      if (c2SRoomInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(C2SRoomInfo);
      }
      s2CRoomInfo_.WriteTo(ref output, _repeated_s2CRoomInfo_codec);
      s2CPlayerInfo_.WriteTo(ref output, _repeated_s2CPlayerInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FuncCode != global::NetMessage.Lobby.FuncCode.FuncNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FuncCode);
      }
      if (ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReturnCode);
      }
      if (ErrorCode != global::NetMessage.Lobby.ErrorCode.ErrorNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
      }
      if (C2SRoomId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(C2SRoomId);
      }
      if (c2SRoomInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(C2SRoomInfo);
      }
      size += s2CRoomInfo_.CalculateSize(_repeated_s2CRoomInfo_codec);
      size += s2CPlayerInfo_.CalculateSize(_repeated_s2CPlayerInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LobbyPack other) {
      if (other == null) {
        return;
      }
      if (other.FuncCode != global::NetMessage.Lobby.FuncCode.FuncNone) {
        FuncCode = other.FuncCode;
      }
      if (other.ReturnCode != global::NetMessage.Enum.ReturnCode.ReturnNone) {
        ReturnCode = other.ReturnCode;
      }
      if (other.ErrorCode != global::NetMessage.Lobby.ErrorCode.ErrorNone) {
        ErrorCode = other.ErrorCode;
      }
      if (other.C2SRoomId.Length != 0) {
        C2SRoomId = other.C2SRoomId;
      }
      if (other.c2SRoomInfo_ != null) {
        if (c2SRoomInfo_ == null) {
          C2SRoomInfo = new global::NetMessage.Lobby.C2SRoomInfo();
        }
        C2SRoomInfo.MergeFrom(other.C2SRoomInfo);
      }
      s2CRoomInfo_.Add(other.s2CRoomInfo_);
      s2CPlayerInfo_.Add(other.s2CPlayerInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FuncCode = (global::NetMessage.Lobby.FuncCode) input.ReadEnum();
            break;
          }
          case 16: {
            ReturnCode = (global::NetMessage.Enum.ReturnCode) input.ReadEnum();
            break;
          }
          case 24: {
            ErrorCode = (global::NetMessage.Lobby.ErrorCode) input.ReadEnum();
            break;
          }
          case 34: {
            C2SRoomId = input.ReadString();
            break;
          }
          case 42: {
            if (c2SRoomInfo_ == null) {
              C2SRoomInfo = new global::NetMessage.Lobby.C2SRoomInfo();
            }
            input.ReadMessage(C2SRoomInfo);
            break;
          }
          case 50: {
            s2CRoomInfo_.AddEntriesFrom(input, _repeated_s2CRoomInfo_codec);
            break;
          }
          case 58: {
            s2CPlayerInfo_.AddEntriesFrom(input, _repeated_s2CPlayerInfo_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FuncCode = (global::NetMessage.Lobby.FuncCode) input.ReadEnum();
            break;
          }
          case 16: {
            ReturnCode = (global::NetMessage.Enum.ReturnCode) input.ReadEnum();
            break;
          }
          case 24: {
            ErrorCode = (global::NetMessage.Lobby.ErrorCode) input.ReadEnum();
            break;
          }
          case 34: {
            C2SRoomId = input.ReadString();
            break;
          }
          case 42: {
            if (c2SRoomInfo_ == null) {
              C2SRoomInfo = new global::NetMessage.Lobby.C2SRoomInfo();
            }
            input.ReadMessage(C2SRoomInfo);
            break;
          }
          case 50: {
            s2CRoomInfo_.AddEntriesFrom(ref input, _repeated_s2CRoomInfo_codec);
            break;
          }
          case 58: {
            s2CPlayerInfo_.AddEntriesFrom(ref input, _repeated_s2CPlayerInfo_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class S2CRoomInfo : pb::IMessage<S2CRoomInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S2CRoomInfo> _parser = new pb::MessageParser<S2CRoomInfo>(() => new S2CRoomInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S2CRoomInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMessage.Lobby.LobbyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CRoomInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CRoomInfo(S2CRoomInfo other) : this() {
      roomId_ = other.roomId_;
      roomName_ = other.roomName_;
      hostName_ = other.hostName_;
      playerNum_ = other.playerNum_;
      maxPlayerNum_ = other.maxPlayerNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2CRoomInfo Clone() {
      return new S2CRoomInfo(this);
    }

    /// <summary>Field number for the "RoomId" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private string roomId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomId {
      get { return roomId_; }
      set {
        roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RoomName" field.</summary>
    public const int RoomNameFieldNumber = 2;
    private string roomName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomName {
      get { return roomName_; }
      set {
        roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HostName" field.</summary>
    public const int HostNameFieldNumber = 3;
    private string hostName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HostName {
      get { return hostName_; }
      set {
        hostName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PlayerNum" field.</summary>
    public const int PlayerNumFieldNumber = 4;
    private int playerNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayerNum {
      get { return playerNum_; }
      set {
        playerNum_ = value;
      }
    }

    /// <summary>Field number for the "MaxPlayerNum" field.</summary>
    public const int MaxPlayerNumFieldNumber = 5;
    private int maxPlayerNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxPlayerNum {
      get { return maxPlayerNum_; }
      set {
        maxPlayerNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S2CRoomInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S2CRoomInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (RoomName != other.RoomName) return false;
      if (HostName != other.HostName) return false;
      if (PlayerNum != other.PlayerNum) return false;
      if (MaxPlayerNum != other.MaxPlayerNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
      if (RoomName.Length != 0) hash ^= RoomName.GetHashCode();
      if (HostName.Length != 0) hash ^= HostName.GetHashCode();
      if (PlayerNum != 0) hash ^= PlayerNum.GetHashCode();
      if (MaxPlayerNum != 0) hash ^= MaxPlayerNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomId);
      }
      if (RoomName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomName);
      }
      if (HostName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HostName);
      }
      if (PlayerNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerNum);
      }
      if (MaxPlayerNum != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxPlayerNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomId);
      }
      if (RoomName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomName);
      }
      if (HostName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HostName);
      }
      if (PlayerNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerNum);
      }
      if (MaxPlayerNum != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxPlayerNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
      }
      if (RoomName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
      }
      if (HostName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HostName);
      }
      if (PlayerNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerNum);
      }
      if (MaxPlayerNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPlayerNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S2CRoomInfo other) {
      if (other == null) {
        return;
      }
      if (other.RoomId.Length != 0) {
        RoomId = other.RoomId;
      }
      if (other.RoomName.Length != 0) {
        RoomName = other.RoomName;
      }
      if (other.HostName.Length != 0) {
        HostName = other.HostName;
      }
      if (other.PlayerNum != 0) {
        PlayerNum = other.PlayerNum;
      }
      if (other.MaxPlayerNum != 0) {
        MaxPlayerNum = other.MaxPlayerNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RoomId = input.ReadString();
            break;
          }
          case 18: {
            RoomName = input.ReadString();
            break;
          }
          case 26: {
            HostName = input.ReadString();
            break;
          }
          case 32: {
            PlayerNum = input.ReadInt32();
            break;
          }
          case 40: {
            MaxPlayerNum = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RoomId = input.ReadString();
            break;
          }
          case 18: {
            RoomName = input.ReadString();
            break;
          }
          case 26: {
            HostName = input.ReadString();
            break;
          }
          case 32: {
            PlayerNum = input.ReadInt32();
            break;
          }
          case 40: {
            MaxPlayerNum = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class C2SRoomInfo : pb::IMessage<C2SRoomInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<C2SRoomInfo> _parser = new pb::MessageParser<C2SRoomInfo>(() => new C2SRoomInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2SRoomInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMessage.Lobby.LobbyReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2SRoomInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2SRoomInfo(C2SRoomInfo other) : this() {
      roomName_ = other.roomName_;
      hostName_ = other.hostName_;
      maxPlayerNum_ = other.maxPlayerNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2SRoomInfo Clone() {
      return new C2SRoomInfo(this);
    }

    /// <summary>Field number for the "RoomName" field.</summary>
    public const int RoomNameFieldNumber = 1;
    private string roomName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomName {
      get { return roomName_; }
      set {
        roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HostName" field.</summary>
    public const int HostNameFieldNumber = 2;
    private string hostName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HostName {
      get { return hostName_; }
      set {
        hostName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MaxPlayerNum" field.</summary>
    public const int MaxPlayerNumFieldNumber = 3;
    private int maxPlayerNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxPlayerNum {
      get { return maxPlayerNum_; }
      set {
        maxPlayerNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2SRoomInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2SRoomInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomName != other.RoomName) return false;
      if (HostName != other.HostName) return false;
      if (MaxPlayerNum != other.MaxPlayerNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RoomName.Length != 0) hash ^= RoomName.GetHashCode();
      if (HostName.Length != 0) hash ^= HostName.GetHashCode();
      if (MaxPlayerNum != 0) hash ^= MaxPlayerNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoomName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomName);
      }
      if (HostName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HostName);
      }
      if (MaxPlayerNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxPlayerNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoomName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoomName);
      }
      if (HostName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HostName);
      }
      if (MaxPlayerNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxPlayerNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RoomName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
      }
      if (HostName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HostName);
      }
      if (MaxPlayerNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPlayerNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2SRoomInfo other) {
      if (other == null) {
        return;
      }
      if (other.RoomName.Length != 0) {
        RoomName = other.RoomName;
      }
      if (other.HostName.Length != 0) {
        HostName = other.HostName;
      }
      if (other.MaxPlayerNum != 0) {
        MaxPlayerNum = other.MaxPlayerNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RoomName = input.ReadString();
            break;
          }
          case 18: {
            HostName = input.ReadString();
            break;
          }
          case 24: {
            MaxPlayerNum = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RoomName = input.ReadString();
            break;
          }
          case 18: {
            HostName = input.ReadString();
            break;
          }
          case 24: {
            MaxPlayerNum = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
